<<<<<<< HEAD
# Generated by Django 3.1.1 on 2020-11-19 03:53
=======
# Generated by Django 3.1.2 on 2020-11-18 15:32
>>>>>>> 86d1c7eee857fb0babd0008ef98353c136c0bf0e

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('parsed_date', models.DateTimeField(blank=True, null=True)),
=======
                ('name', models.CharField(default='', max_length=100, verbose_name='Название статьи')),
                ('content', models.TextField(verbose_name='Содержание статьи')),
                ('author', models.CharField(max_length=100, verbose_name='Автор статьи')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата публикации статьи')),
                ('parsed_date', models.DateField(blank=True, null=True, verbose_name='Дата разбора с сайта')),
>>>>>>> 86d1c7eee857fb0babd0008ef98353c136c0bf0e
                ('original_link', models.CharField(default='', max_length=255, verbose_name='Источник статьи')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(max_length=255)),
=======
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
>>>>>>> 86d1c7eee857fb0babd0008ef98353c136c0bf0e
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название источника')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(blank=True, null=True, upload_to='articles_images', verbose_name='Изображение')),
                ('original_path', models.TextField(verbose_name='Исходный путь изображения')),
<<<<<<< HEAD
                ('position', models.IntegerField(verbose_name='Порядок')),
=======
                ('position', models.IntegerField(default=0, verbose_name='Очередность изображения в тексте статьи')),
>>>>>>> 86d1c7eee857fb0babd0008ef98353c136c0bf0e
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
<<<<<<< HEAD
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
=======
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category'),
>>>>>>> 86d1c7eee857fb0babd0008ef98353c136c0bf0e
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.source'),
        ),
    ]
