# Generated by Django 3.1.1 on 2020-11-03 04:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='publication_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='referer_url',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='source',
        ),
        migrations.AddField(
            model_name='article',
            name='parsed_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
