# Generated by Django 3.1.1 on 2020-11-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201103_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='parsed_date',
            field=models.CharField(max_length=255),
        ),
    ]
